name: Build

on:
  repository_dispatch:
    types: [start-yt-download]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependency
        run: |
          npm install

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1

      - uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: setup_ffmpeg

      - name: Start job
        run: |
          node index.js -u "${{ github.event.client_payload.url }}" -s "${{ github.event.client_payload.singer }}" -n "${{ github.event.client_payload.name }}" -a "${{ secrets.QINIU_KEY }}"  -S "${{ secrets.QINIU_SECRET }}"   -e "${{ secrets.ENT_POINT }}"  -b "${{ secrets.QINIU_BUCKET }}" -q "${{ secrets.QINIU_POINT }}" -U "${{ secrets.YI_USER }}" -P "${{ secrets.YI_PASSWORD }}" -f ${{ steps.setup_ffmpeg.outputs.ffmpeg-path }}
          
