name: Build

on:
  repository_dispatch:
    types: [start-yt-download]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install dependency
        run: |
          npm install ytb2mp3@latest --save
          npm install ytdl-core@latest --save
          npm install

      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: setup-ffmpeg

      - name: Start job
        run: |
          node index.js -u "${{ github.event.client_payload.url }}" -s "${{ github.event.client_payload.singer }}" -n "${{ github.event.client_payload.name }}" -a "${{ github.event.client_payload.access_key }}"  -S "${{ github.event.client_payload.secret }}"   -e "${{ github.event.client_payload.end_point }}"  -b "${{ github.event.client_payload.bucket }}" -q "${{ github.event.client_payload.qiniu_point }}" -U "${{ github.event.client_payload.user }}" -P "${{ github.event.client_payload.password }}"
